spring.application.name=frontend-service
server.port=8080


# Other services
auth.service.url=http://localhost:8083
pet.service.url=http://localhost:8081
item.service.url=http://localhost:8082
export.service.url=http://localhost:8085

# Thymeleaf
spring.thymeleaf.cache=false
